backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "carousel"
    label: "Carrusel"
    folder: "public/data"
    create: true
    slug: "carousel"
    format: "json"
    extension: "json"
    editor:
      preview: false
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "image", label: "Imagen", widget: "image" }
