backend:
  name: github
  repo: https://github.com/Andres-ff/Prueba.git
  auth_type: implicit
  app_id: zUE7eUCZzBEJtPELVbK6vOESomY5m878
  base_url: https://juandomingoprueba.netlify.app
  auth_endpoint: https://juandomingoprueba.netlify.app/authorize


media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "carousel"
    label: "Carrusel"
    folder: "src/data/carousel"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
